Update workflow.yaml

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -1,48 +1,36 @@
-name: Check Pull Request
-on: pull_request
+name: PR-check
+on:
+  pull_request:
+    types: [opened, reopened, synchronize]
+    branches:
+    - main
+    - prod
+    - staging
+
+env:
+  VALIDWAY: 'dev-staging staging-prod staging-main'
 
 jobs:
-  check_pr:
-    runs-on: ubuntu-latest
-
+  merge-order-check:
+    runs-on: solinas
     steps:
-      - name: Check if PR target branch is ok
-        run: |
-          branch_name=${GITHUB_HEAD_REF}
-          echo "pr branch name: $branch_name"
-          
-          target_branch=${GITHUB_BASE_REF}
-          echo "target branch: $target_branch"
-          dev_regex="^(bug|feature|code-cleanup)/JIRA-.+$"
-          qa_regex="^kickback/JIRA-.+$"
-          
-          if [[ "$branch_name" =~ $dev_regex ]]; then
-            echo "Branch name matches the first regex pattern."
-            if [[ "$target_branch" != "dev" ]]; then
-              echo "but doesn't match target branch"
-              exit 1
-            fi
-          elif [[ "$branch_name" =~ $qa_regex ]]; then
-            echo "Branch name matches the second regex pattern."
-            if [[ "$target_branch" != "dev" ]]; then
-              echo "but doesn't match target branch"
-              exit 1
-            fi
-          else
-            echo "Branch name does not match any regex. Exiting..."
-            exit 1
-          fi
-        shell: bash
+      - name: export
+        run: 
+          export
+
       - name: debug
         run: |
-          echo sha: ${{ steps.comment-branch.outputs.head_sha }}
-          echo token: ${{ secrets.GITHUB_TOKEN }}
-          echo status: ${{ job.status }}
-
-      - name: Set final commit status
-        uses: myrotvorets/set-commit-status-action@master
-        if: always()
-        with:
-          sha: ${{ steps.comment-branch.outputs.head_sha }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          status: ${{ job.status }}
+          echo --------- some debug ---------
+          export CURRENTSETUP=$GITHUB_HEAD_REF-$GITHUB_BASE_REF
+          echo valid $VALIDWAY
+          echo current $CURRENTSETUP
+          echo github.event.pull_request.head.sha ${{ github.event.pull_request.head.sha }}
+          echo github.event.before ${{ github.event.before }}
+          echo github.event.after ${{ github.event.after }}
+          echo GITHUB_WORKFLOW_SHA $GITHUB_WORKFLOW_SHA
+          echo GITHUB_WORKFLOW_REF $GITHUB_WORKFLOW_REF
+  
+      - name: merge-order-check
+        run: |
+          echo "$GITHUB_HEAD_REF-$GITHUB_BASE_REF In case of error, branch merge order is wrong, check readme";
+          [[ $VALIDWAY =~ (^|[[:space:]])$GITHUB_HEAD_REF-$GITHUB_BASE_REF($|[[:space:]]) ]] && echo 'All ok' || exit 1
